%YAML:1.0  //用cv::FileStorage读取YAML文件必须加这个

imu_topic: "/imu0"
image_topic: "/cam0/image_raw"

image_width: 752
image_height: 480
distorrion_parameters: [-2.917e-01, 8.228e-02, 5.333e-05, -1.578e-04]
intrinsics: [4.616e+02, 4.603e+02, 3.630e+02, 2.481e+02]

max_cut: 150
min_dist: 30
track_intensity: 20
